add docker file + some seeding. Functionality needs refactoring

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -1,8 +1,24 @@
-#!/bin/bash -e
+#!/bin/bash
+set -e
 
-# If running the rails server then create or migrate existing database
-if [ "${1}" == "./bin/rails" ] && [ "${2}" == "server" ]; then
-  ./bin/rails db:prepare
+# Remove a potentially pre-existing server.pid for Rails.
+rm -f /rails/tmp/pids/server.pid
+
+# Ensure the master key is in place
+if [ ! -f /rails/config/master.key ]; then
+  echo "Master key is missing, copying from secret..."
+  cp /run/secrets/master_key /rails/config/master.key
 fi
 
-exec "${@}"
+# Setup database
+echo "Running database setup..."
+bundle exec rails db:prepare
+
+# Precompile assets if needed
+if [ "$RAILS_ENV" == "production" ]; then
+  echo "Precompiling assets..."
+  bundle exec rails assets:precompile
+fi
+
+# Then exec the container's main process (what's set as CMD in the Dockerfile).
+exec "$@"
